/**
 * app/stock/[ticker]/page.tsx — RayZar Frontend
 * Stock detail page: TradingView candlestick chart + signal metadata.
 *
 * Server Component — data fetched at request time (revalidate: 60s).
 * Chart is a Client Component (requires browser canvas APIs).
 *
 * DATA NOTE:
 * OHLCV data originates from the nightly IBKR pipeline on the owner's Mac.
 * Signal data is generated by the ML pipeline and stored in AWS RDS.
 * This page is READ-ONLY — it never writes to the backend.
 */

import Link from "next/link";
import { ArrowLeft } from "lucide-react";
import { notFound } from "next/navigation";
import { apiClient } from "@/lib/api-client";
import { OhlcvChart } from "@/features/charts/components/ohlcv-chart";
import { SignalDetailCard } from "@/features/signals/components/signal-detail-card";
import { FINANCIAL_DISCLAIMER } from "@/config/legal";

interface StockPageProps {
  params: Promise<{ ticker: string }>;
}

export async function generateMetadata({ params }: StockPageProps) {
  const { ticker } = await params;
  return {
    title: `${ticker.toUpperCase()} — RayZar`,
    description: `RayZar signal and chart data for ${ticker.toUpperCase()}`,
  };
}

export default async function StockPage({ params }: StockPageProps) {
  const { ticker } = await params;
  const upper = ticker.toUpperCase();

  // Fetch signal + OHLCV in parallel
  const [signalRes, ohlcvRes] = await Promise.allSettled([
    apiClient.getSignalByTicker(upper),
    apiClient.getOhlcv(upper, 252),
  ]);

  const signal =
    signalRes.status === "fulfilled" && signalRes.value.success
      ? signalRes.value.data
      : null;

  const bars =
    ohlcvRes.status === "fulfilled" && ohlcvRes.value.success
      ? (ohlcvRes.value.data ?? [])
      : [];

  // 404 if the ticker has never had a signal (bad URL or typo)
  if (!signal && bars.length === 0) {
    notFound();
  }

  return (
    <main className="min-h-screen bg-[#050505] text-white">
      <div className="mx-auto max-w-5xl px-4 py-8 sm:px-6">

        {/* ── Back link ──────────────────────────────────────────────────── */}
        <Link
          href="/dashboard"
          className="inline-flex items-center gap-1.5 text-sm text-gray-400 hover:text-white transition-colors mb-6"
        >
          <ArrowLeft className="h-4 w-4" />
          Back to dashboard
        </Link>

        {/* ── Header ─────────────────────────────────────────────────────── */}
        <div className="mb-6">
          <h1 className="text-3xl font-bold text-white">{upper}</h1>
          {signal && (
            <p className="text-sm text-gray-500 mt-1">
              Signal as of {signal.signal_date}
            </p>
          )}
        </div>

        {/* ── Chart ──────────────────────────────────────────────────────── */}
        <div className="mb-6">
          <div className="flex items-center justify-between mb-3">
            <h2 className="text-sm font-medium text-gray-400 uppercase tracking-wider">
              Price Chart · Daily
            </h2>
            {bars.length > 0 && (
              <span className="text-xs text-gray-600">
                {bars.length} bars · SMA 20 / SMA 50
              </span>
            )}
          </div>
          <OhlcvChart bars={bars} ticker={upper} />
        </div>

        {/* ── Signal card ────────────────────────────────────────────────── */}
        {signal ? (
          <div className="mb-6">
            <h2 className="text-sm font-medium text-gray-400 uppercase tracking-wider mb-3">
              Signal Detail
            </h2>
            <SignalDetailCard signal={signal} />
          </div>
        ) : (
          <div className="mb-6 rounded-lg border border-[#1a1a1a] bg-[#0f0f0f] p-5 text-sm text-gray-500">
            No signal found for {upper}. It may not be in the current watchlist.
          </div>
        )}

        {/* ── Disclaimer ─────────────────────────────────────────────────── */}
        <p className="text-xs text-gray-600 leading-relaxed border-t border-[#1a1a1a] pt-6">
          {FINANCIAL_DISCLAIMER}
        </p>
      </div>
    </main>
  );
}
