/**
 * app/stock/[ticker]/page.tsx — RayZar Frontend
 * Full trading terminal view for a single ticker.
 *
 * Server Component — data fetched at request time (revalidate: 60s).
 * Chart and interactive panels are Client Components.
 *
 * DATA NOTE:
 * OHLCV data originates from the nightly IBKR pipeline on the owner's Mac.
 * Signal + TA data are generated by the ML pipeline and stored in AWS RDS.
 * This page is READ-ONLY — it never writes to the backend.
 */

import Link from "next/link";
import { ArrowLeft, TrendingUp, TrendingDown, Minus } from "lucide-react";
import { notFound } from "next/navigation";
import { apiClient } from "@/lib/api-client";
import { parseFeatureContext } from "@/lib/api-client";
import type { Signal, TAAnalysisResponse, TASignalItem, EarningsQuarter, OptionsSnapshot, InsiderActivity } from "@/lib/api-client";
import { TradingChart } from "@/features/charts/components/trading-chart";
import { WorkspaceLayout } from "@/features/workspace/workspace-layout";
import { StockPageTabs } from "@/features/stock/components/stock-page-tabs";
import { AdvancedTabContent } from "@/features/stock/components/advanced-tab-content";
import { HealthScoreBar } from "@/components/ui/health-score-bar";
import { TASignalsPanel } from "@/components/ui/ta-signals-panel";
import { AnalystPanel } from "@/components/ui/analyst-panel";
import { PatternBadge } from "@/components/ui/pattern-badge";
import { SignalBadge } from "@/components/ui/signal-badge";
import { RayzarScore } from "@/components/ui/rayzar-score";
import { WatchButton } from "@/components/ui/watch-button";
import { FINANCIAL_DISCLAIMER } from "@/config/legal";
import { cn } from "@/lib/utils";

interface StockPageProps {
  params: Promise<{ ticker: string }>;
}

export async function generateMetadata({ params }: StockPageProps) {
  const { ticker } = await params;
  const upper = ticker.toUpperCase();
  return {
    title: `${upper} — RayZar AI`,
    description: `RayZar AI signal, TA analysis, and chart data for ${upper}`,
  };
}

// ── Probability bar ───────────────────────────────────────────────────────────
function ProbBar({
  label,
  value,
  color,
}: {
  label: string;
  value: number | null;
  color: string;
}) {
  const pct = value !== null ? Math.round(value * 100) : null;
  return (
    <div className="flex items-center gap-2">
      <span className="w-14 shrink-0 text-xs text-text-secondary">{label}</span>
      <div className="h-2 flex-1 overflow-hidden rounded-full bg-elevated">
        <div
          className="h-full rounded-full transition-all duration-700"
          style={{
            width: pct !== null ? `${pct}%` : "0%",
            background: color,
          }}
        />
      </div>
      <span className="w-8 text-right font-mono text-xs text-text-secondary">
        {pct !== null ? `${pct}%` : "—"}
      </span>
    </div>
  );
}

// ── Metrics grid item ────────────────────────────────────────────────────────
function MetricCell({
  label,
  value,
  mono = true,
  highlight,
}: {
  label: string;
  value: string | null | undefined;
  mono?: boolean;
  highlight?: string;
}) {
  return (
    <div className="rounded-lg border border-border bg-card/50 p-3">
      <p className="text-2xs text-text-muted">{label}</p>
      <p
        className={cn(
          "mt-0.5 text-sm font-semibold",
          mono && "font-mono",
          !value && "text-text-muted"
        )}
        style={highlight ? { color: highlight } : undefined}
      >
        {value ?? "—"}
      </p>
    </div>
  );
}

// ── Regime badge ─────────────────────────────────────────────────────────────
function RegimePill({ label, type = "neutral" }: { label: string; type?: "bull" | "bear" | "neutral" | "recovering" }) {
  const colors: Record<string, string> = {
    bull:       "#10b981",
    recovering: "#f59e0b",
    neutral:    "#6b7280",
    bear:       "#ef4444",
  };
  const color = colors[type] ?? colors.neutral;
  return (
    <span
      className="inline-flex items-center gap-1.5 rounded border px-2 py-0.5 text-xs font-medium"
      style={{ color, background: `${color}15`, borderColor: `${color}30` }}
    >
      <span className="h-1.5 w-1.5 rounded-full" style={{ background: color }} />
      {label}
    </span>
  );
}

function getRegimeType(label: string | null): "bull" | "bear" | "neutral" | "recovering" {
  if (!label) return "neutral";
  const l = label.toLowerCase();
  if (l.includes("bull") || l.includes("risk-on")) return "bull";
  if (l.includes("bear") || l.includes("risk-off")) return "bear";
  if (l.includes("recover") || l.includes("transition")) return "recovering";
  return "neutral";
}

// ── Pattern badges row ────────────────────────────────────────────────────────
function buildPatternBadges(
  taSignals: TASignalItem[],
  features: ReturnType<typeof parseFeatureContext>
): { name: string; direction: "bullish" | "bearish" | "neutral"; confidence: number; timeframe: string }[] {
  const patterns: { name: string; direction: "bullish" | "bearish" | "neutral"; confidence: number; timeframe: string }[] = [];

  // From TA analysis signals (first 3 that look like patterns)
  for (const sig of taSignals.slice(0, 5)) {
    patterns.push({
      name: sig.name,
      direction: sig.direction,
      confidence: sig.confidence,
      timeframe: sig.timeframe,
    });
    if (patterns.length >= 4) break;
  }

  // Supplement with pattern_1/2/3 from features_used if not enough
  if (features) {
    const pats = [features.pattern_1, features.pattern_2, features.pattern_3].filter(Boolean) as string[];
    for (const p of pats) {
      if (patterns.find((x) => x.name === p)) continue;
      patterns.push({ name: p, direction: "neutral", confidence: 0.5, timeframe: "1d" });
      if (patterns.length >= 5) break;
    }
  }

  return patterns;
}

function formatLargeNumber(n: number | null): string {
  if (n === null) return "—";
  if (n >= 1e12) return `$${(n / 1e12).toFixed(2)}T`;
  if (n >= 1e9)  return `$${(n / 1e9).toFixed(2)}B`;
  if (n >= 1e6)  return `$${(n / 1e6).toFixed(2)}M`;
  return `$${n.toFixed(2)}`;
}

// ── Sector ETF mapping ────────────────────────────────────────────────────────
const SECTOR_ETF: Record<string, string> = {
  "Technology":              "XLK",
  "Financial Services":      "XLF",
  "Financials":              "XLF",
  "Healthcare":              "XLV",
  "Health Care":             "XLV",
  "Energy":                  "XLE",
  "Consumer Cyclical":       "XLY",
  "Consumer Discretionary":  "XLY",
  "Consumer Defensive":      "XLP",
  "Consumer Staples":        "XLP",
  "Industrials":             "XLI",
  "Basic Materials":         "XLB",
  "Materials":               "XLB",
  "Real Estate":             "XLRE",
  "Utilities":               "XLU",
  "Communication Services":  "XLC",
};

export default async function StockPage({ params }: StockPageProps) {
  const { ticker } = await params;
  const upper = ticker.toUpperCase();

  // Fetch all data in parallel
  const [signalRes, ohlcvRes, fundamentalsRes, taAnalysisRes, earningsRes, optionsRes, insiderRes] = await Promise.allSettled([
    apiClient.getSignalByTicker(upper),
    apiClient.getOhlcv(upper, 365),
    apiClient.getFundamentals(upper),
    apiClient.getTAAnalysis(upper),
    apiClient.getEarnings(upper),
    apiClient.getOptions(upper),
    apiClient.getInsiderActivity(upper),
  ]);

  const signal: Signal | null =
    signalRes.status === "fulfilled" && signalRes.value.success
      ? signalRes.value.data
      : null;

  const bars =
    ohlcvRes.status === "fulfilled" && ohlcvRes.value.success
      ? (ohlcvRes.value.data ?? [])
      : [];

  const fundamentals =
    fundamentalsRes.status === "fulfilled" && fundamentalsRes.value.success
      ? fundamentalsRes.value.data
      : null;

  const taAnalysis: TAAnalysisResponse | null =
    taAnalysisRes.status === "fulfilled" ? taAnalysisRes.value : null;

  const earningsHistory: EarningsQuarter[] =
    earningsRes.status === "fulfilled" && earningsRes.value.success
      ? (earningsRes.value.data ?? [])
      : [];

  const optionsSnapshot: OptionsSnapshot | null =
    optionsRes.status === "fulfilled" && optionsRes.value.success
      ? optionsRes.value.data ?? null
      : null;

  const insiderActivity: InsiderActivity | null =
    insiderRes.status === "fulfilled" && insiderRes.value.success
      ? insiderRes.value.data ?? null
      : null;

  // 404 if nothing exists for this ticker
  if (!signal && bars.length === 0) {
    notFound();
  }

  // Parse features_used from signal for fallback data
  const features = signal ? parseFeatureContext(signal.features_used) : null;

  // Fetch sector ETF bars for relative strength sub-pane
  const sectorName = signal?.sector ?? fundamentals?.sector ?? null;
  const sectorEtf = sectorName ? (SECTOR_ETF[sectorName] ?? null) : null;
  const sectorBars = sectorEtf
    ? await apiClient.getOhlcv(sectorEtf, 365).then((r) => (r.success ? (r.data ?? []) : [])).catch(() => [])
    : [];

  // Compose TA data: prefer backend taAnalysis, fall back to features_used
  const healthScore = taAnalysis?.health_score ?? features?.health_score ?? null;
  const healthGrade = taAnalysis?.health_grade ?? features?.health_grade ?? null;
  const personality = taAnalysis?.personality_type ?? features?.personality_type ?? null;
  const macroRegime = taAnalysis?.macro_regime_label ?? features?.macro_regime ?? null;
  const sectorRegime = taAnalysis?.sector_regime_label ?? features?.sector_regime ?? null;
  const taDirection = taAnalysis?.ta_direction ?? (features?.ta_direction as "bullish" | "bearish" | "neutral" | null) ?? null;
  const taSummary = taAnalysis?.ta_summary ?? features?.ta_summary ?? null;
  const taSignals: TASignalItem[] = taAnalysis?.signals ?? [];
  const longProb = features?.long_prob ?? null;
  const shortProb = features?.short_prob ?? null;
  const hurstExp = features?.hurst_exponent ?? null;
  const fundBeta = features?.beta ?? fundamentals?.beta ?? null;

  // Current price
  const currentPrice = bars.length > 0 ? bars[bars.length - 1].close : null;
  const prevPrice = bars.length > 1 ? bars[bars.length - 2].close : null;
  const priceChange = currentPrice && prevPrice ? currentPrice - prevPrice : null;
  const priceChangePct = currentPrice && prevPrice ? ((currentPrice - prevPrice) / prevPrice) * 100 : null;
  const isPositive = priceChange !== null ? priceChange >= 0 : null;

  // Pattern badges row
  const patternBadges = buildPatternBadges(taSignals, features);

  // ── 4-pane workspace content ──────────────────────────────────────────────

  // Pane 1 — top-left: Trading chart
  const paneChart = (
    <TradingChart
      bars={bars}
      ticker={upper}
      taAnalysis={taAnalysis}
      signal={signal}
      earningsHistory={earningsHistory}
      optionsSnapshot={optionsSnapshot}
      insiderActivity={insiderActivity}
      sectorBars={sectorBars}
      sectorEtf={sectorEtf}
      height={500}
    />
  );

  // Key levels from TA analysis
  const keyLevels = taAnalysis?.signals?.length
    ? (() => {
        const support: number[] = [];
        const resistance: number[] = [];
        for (const sig of taAnalysis.signals) {
          if (!sig.key_levels) continue;
          const kl = sig.key_levels as Record<string, number>;
          if (typeof kl.support === "number") support.push(kl.support);
          if (typeof kl.resistance === "number") resistance.push(kl.resistance);
          if (typeof kl.stop_loss === "number") support.push(kl.stop_loss);
          if (typeof kl.target === "number") resistance.push(kl.target);
        }
        return {
          support: support.length ? Math.min(...support) : null,
          resistance: resistance.length ? Math.max(...resistance) : null,
          stop: support.length ? Math.min(...support) : null,
          target: resistance.length ? Math.max(...resistance) : null,
        };
      })()
    : null;

  // Pane 2 — top-right: Signal summary + health + personality + regime
  const paneSignal = (
    <>
      {signal && (
        <div className="rounded-lg border border-border bg-card p-4 space-y-3">
          <div className="flex items-center justify-between">
            <h3 className="text-xs font-semibold uppercase tracking-wider text-text-muted">Signal</h3>
            <span className="font-mono text-sm font-bold" style={{ color: signal.confidence >= 0.65 ? "#10b981" : signal.confidence >= 0.55 ? "#f59e0b" : "#6b7280" }}>
              {Math.round(signal.confidence * 100)}% confidence
            </span>
          </div>
          <ProbBar label="Long Prob" value={longProb ?? signal.confidence} color="#10b981" />
          <ProbBar
            label="Short Prob"
            value={shortProb ?? (signal.signal_class === "SHORT" || signal.signal_class === "STRONG_SHORT" ? signal.confidence : null)}
            color="#ef4444"
          />
          {signal.reasoning && (
            <p className="text-xs leading-relaxed text-text-secondary border-t border-border pt-2">
              {signal.reasoning}
            </p>
          )}
        </div>
      )}

      {/* Short signal confidence warning */}
      {(signal?.signal_class === "SHORT" || signal?.signal_class === "STRONG_SHORT") && (
        <div className="rounded-lg border border-red-500/40 bg-red-500/10 p-4">
          <p className="text-xs font-medium text-red-400">
            ⚠️ Short signals have lower validated accuracy (56% directional vs 73% for Strong Long). Only generated in confirmed bear market conditions (SPY below key moving averages). Treat with higher caution and tighter position sizing.
          </p>
        </div>
      )}

      {/* Earnings proximity warning */}
      {features?.earnings_proximity_flag && (
        <div className="rounded-lg border border-amber-500/40 bg-amber-500/10 p-4">
          <p className="text-xs font-medium text-amber-400">
            ⚠️ {features.days_to_earnings != null ? `Earnings in ${features.days_to_earnings} day${features.days_to_earnings === 1 ? "" : "s"}` : "Earnings approaching"} — ML signal does not account for binary event risk. Consider reducing size.
          </p>
        </div>
      )}

      {/* Key levels */}
      {keyLevels && (keyLevels.support !== null || keyLevels.resistance !== null) && (
        <div className="rounded-lg border border-border bg-card p-4 space-y-2">
          <h3 className="text-xs font-semibold uppercase tracking-wider text-text-muted">Key Levels</h3>
          {[
            { label: "Resistance", value: keyLevels.resistance, color: "#ef4444" },
            { label: "Target",     value: keyLevels.target,     color: "#10b981" },
            { label: "Support",    value: keyLevels.support,    color: "#10b981" },
            { label: "Stop Loss",  value: keyLevels.stop,       color: "#ef4444" },
          ].filter((l) => l.value !== null).map(({ label, value, color }) => (
            <div key={label} className="flex items-center justify-between">
              <span className="text-xs text-text-muted">{label}</span>
              <span className="font-mono text-xs font-semibold" style={{ color }}>
                ${(value as number).toFixed(2)}
              </span>
            </div>
          ))}
        </div>
      )}

      {/* TA + ML Alignment */}
      {features?.ta_alignment_status && (
        <div className="rounded-lg border border-border bg-card p-4 space-y-2">
          <h3 className="text-xs font-semibold uppercase tracking-wider text-text-muted">TA + ML Alignment</h3>
          {(() => {
            const status = features.ta_alignment_status;
            const badgeMap: Record<string, { label: string; color: string; bg: string; border: string }> = {
              STRONG_AGREE:    { label: "✓ Strong Agree",   color: "#10b981", bg: "#10b98115", border: "#10b98130" },
              WEAK_AGREE:      { label: "~ Weak Agree",     color: "#6ee7b7", bg: "#6ee7b715", border: "#6ee7b730" },
              NEUTRAL:         { label: "— Neutral",        color: "#6b7280", bg: "#6b728015", border: "#6b728030" },
              WEAK_CONFLICT:   { label: "⚠ Weak Conflict",  color: "#f59e0b", bg: "#f59e0b15", border: "#f59e0b30" },
              STRONG_CONFLICT: { label: "✗ Strong Conflict", color: "#ef4444", bg: "#ef444415", border: "#ef444430" },
            };
            const badge = badgeMap[status ?? ""] ?? { label: status, color: "#6b7280", bg: "#6b728015", border: "#6b728030" };
            return (
              <>
                <span
                  className="inline-flex items-center rounded border px-2 py-0.5 text-xs font-semibold"
                  style={{ color: badge.color, background: badge.bg, borderColor: badge.border }}
                >
                  {badge.label}
                </span>
                {features.ta_conflict_reason && (
                  <p className="text-2xs text-text-muted leading-relaxed">{features.ta_conflict_reason}</p>
                )}
              </>
            );
          })()}
        </div>
      )}

      {/* Risk Management — ATR stops + position sizing */}
      {(features?.stop_loss !== null && features?.stop_loss !== undefined ||
        features?.target_1 !== null && features?.target_1 !== undefined ||
        features?.target_2 !== null && features?.target_2 !== undefined ||
        features?.risk_pct !== null && features?.risk_pct !== undefined ||
        features?.shares_1pct_risk !== null && features?.shares_1pct_risk !== undefined) && (
        <div className="rounded-lg border border-border bg-card p-4 space-y-2">
          <h3 className="text-xs font-semibold uppercase tracking-wider text-text-muted">Risk Management</h3>
          {features?.stop_loss !== null && features?.stop_loss !== undefined && (
            <div className="flex items-center justify-between">
              <span className="text-xs text-text-muted">Stop Loss</span>
              <span className="font-mono text-xs font-semibold" style={{ color: "#ef4444" }}>
                ${(features.stop_loss as number).toFixed(2)}
              </span>
            </div>
          )}
          {features?.target_1 !== null && features?.target_1 !== undefined && (
            <div className="flex items-center justify-between">
              <span className="text-xs text-text-muted">Target 1</span>
              <span className="font-mono text-xs font-semibold" style={{ color: "#10b981" }}>
                ${(features.target_1 as number).toFixed(2)}
              </span>
            </div>
          )}
          {features?.target_2 !== null && features?.target_2 !== undefined && (
            <div className="flex items-center justify-between">
              <span className="text-xs text-text-muted">Target 2</span>
              <span className="font-mono text-xs font-semibold" style={{ color: "#10b981" }}>
                ${(features.target_2 as number).toFixed(2)}
              </span>
            </div>
          )}
          {features?.risk_pct !== null && features?.risk_pct !== undefined && (
            <div className="flex items-center justify-between">
              <span className="text-xs text-text-muted">Risk/Trade</span>
              <span className="font-mono text-xs text-text-primary">
                {(features.risk_pct as number).toFixed(2)}%
              </span>
            </div>
          )}
          {features?.shares_1pct_risk !== null && features?.shares_1pct_risk !== undefined && (
            <div className="flex items-center justify-between">
              <span className="text-xs text-text-muted">Shares (1% risk)</span>
              <span className="font-mono text-xs text-text-primary">
                {Math.round(features.shares_1pct_risk as number)}
              </span>
            </div>
          )}
        </div>
      )}

      <div className="rounded-lg border border-border bg-card p-4">
        <h3 className="mb-3 text-xs font-semibold uppercase tracking-wider text-text-muted">TA Health Score</h3>
        <HealthScoreBar score={healthScore} grade={healthGrade} size="lg" />
      </div>

      {(personality || hurstExp !== null || fundBeta !== null) && (
        <div className="rounded-lg border border-border bg-card p-4 space-y-3">
          <h3 className="text-xs font-semibold uppercase tracking-wider text-text-muted">Stock Personality</h3>
          {personality && (
            <div className="flex items-center justify-between">
              <span className="text-xs text-text-secondary">Type</span>
              <span className="rounded border border-border bg-elevated px-2 py-0.5 font-mono text-xs font-semibold text-accent-teal">
                {personality}
              </span>
            </div>
          )}
          {fundBeta !== null && (
            <div className="flex items-center justify-between">
              <span className="text-xs text-text-secondary">Beta</span>
              <span className="font-mono text-xs text-text-primary">{fundBeta.toFixed(2)}</span>
            </div>
          )}
          {hurstExp !== null && (
            <div className="flex items-center justify-between">
              <span className="text-xs text-text-secondary">Hurst Exp.</span>
              <span className="font-mono text-xs text-text-primary">{hurstExp.toFixed(2)}</span>
            </div>
          )}
        </div>
      )}

      {(macroRegime || sectorRegime) && (
        <div className="rounded-lg border border-border bg-card p-4 space-y-3">
          <h3 className="text-xs font-semibold uppercase tracking-wider text-text-muted">Market Regime</h3>
          {macroRegime && (
            <div className="flex items-center justify-between">
              <span className="text-xs text-text-secondary">Macro</span>
              <RegimePill label={macroRegime} type={getRegimeType(macroRegime)} />
            </div>
          )}
          {sectorRegime && (
            <div className="flex items-center justify-between">
              <span className="text-xs text-text-secondary">Sector</span>
              <RegimePill label={sectorRegime} type={getRegimeType(sectorRegime)} />
            </div>
          )}
          {signal?.regime && (
            <div className="flex items-center justify-between">
              <span className="text-xs text-text-secondary">Signal Regime</span>
              <span className="text-xs text-text-primary">{signal.regime}</span>
            </div>
          )}
        </div>
      )}
    </>
  );

  // Pane 3 — bottom-left: Patterns + Fundamentals + Earnings + Options
  const paneData = (
    <>
      {patternBadges.length > 0 && (
        <div>
          <div className="mb-2 flex items-center justify-between">
            <h2 className="text-xs font-semibold uppercase tracking-wider text-text-muted">Detected Patterns</h2>
            <span className="text-2xs text-text-muted italic">Contextual — not used as primary signal</span>
          </div>
          <div className="flex flex-wrap gap-2">
            {patternBadges.map((p, i) => (
              <PatternBadge key={`${p.name}-${i}`} name={p.name} direction={p.direction} confidence={p.confidence} timeframe={p.timeframe} />
            ))}
          </div>
          <p className="mt-2 text-2xs text-text-muted leading-relaxed">
            Pattern confidence reflects detection quality, not predictive accuracy. Use alongside ML signal and TA alignment — not in isolation.
          </p>
        </div>
      )}

      {fundamentals && (
        <div>
          <h2 className="mb-2 text-xs font-semibold uppercase tracking-wider text-text-muted">Fundamentals</h2>
          <div className="grid grid-cols-2 gap-2 sm:grid-cols-3 xl:grid-cols-4">
            <MetricCell label="Market Cap"  value={formatLargeNumber(fundamentals.market_cap)} />
            <MetricCell label="P/E Ratio"   value={fundamentals.pe_ratio?.toFixed(1) ?? null} />
            <MetricCell label="P/S Ratio"   value={fundamentals.ps_ratio?.toFixed(1) ?? null} />
            <MetricCell label="P/B Ratio"   value={fundamentals.pb_ratio?.toFixed(1) ?? null} />
            <MetricCell label="Revenue TTM" value={formatLargeNumber(fundamentals.revenue_ttm)} />
            <MetricCell
              label="Net Margin"
              value={fundamentals.profit_margin !== null ? `${(fundamentals.profit_margin * 100).toFixed(1)}%` : null}
              highlight={
                fundamentals.profit_margin !== null
                  ? fundamentals.profit_margin >= 0.15 ? "#10b981"
                  : fundamentals.profit_margin >= 0 ? "#f59e0b"
                  : "#ef4444"
                  : undefined
              }
            />
            <MetricCell label="EPS TTM"    value={fundamentals.eps_ttm?.toFixed(2) ?? null} />
            <MetricCell label="Beta"        value={fundamentals.beta?.toFixed(2) ?? (fundBeta !== null ? fundBeta.toFixed(2) : null)} />
            <MetricCell label="Short Float" value={fundamentals.short_float !== null ? `${(fundamentals.short_float * 100).toFixed(1)}%` : null} />
            <MetricCell label="Div Yield"   value={fundamentals.dividend_yield !== null ? `${(fundamentals.dividend_yield * 100).toFixed(2)}%` : null} />
            <MetricCell label="52W High"    value={fundamentals.week_52_high?.toFixed(2) ?? null} />
            <MetricCell label="52W Low"     value={fundamentals.week_52_low?.toFixed(2) ?? null} />
          </div>
          {fundamentals.earnings_date && (
            <p className="mt-2 text-xs text-text-muted">Next earnings: <span className="text-text-secondary">{fundamentals.earnings_date}</span></p>
          )}
        </div>
      )}

      {earningsHistory.length > 0 && (
        <div>
          <h2 className="mb-2 text-xs font-semibold uppercase tracking-wider text-text-muted">Earnings History</h2>
          <div className="overflow-x-auto rounded-lg border border-border">
            <table className="w-full text-xs">
              <thead>
                <tr className="border-b border-border bg-elevated">
                  <th className="px-3 py-2 text-left font-semibold text-text-muted">Report Date</th>
                  <th className="px-3 py-2 text-right font-semibold text-text-muted">EPS Actual</th>
                  <th className="px-3 py-2 text-right font-semibold text-text-muted">EPS Est.</th>
                  <th className="px-3 py-2 text-right font-semibold text-text-muted">Surprise</th>
                </tr>
              </thead>
              <tbody>
                {earningsHistory.slice(0, 4).map((row) => {
                  const surprise = row.eps_surprise_pct;
                  const surpriseColor = surprise === null ? undefined : surprise >= 0 ? "#10b981" : "#ef4444";
                  return (
                    <tr key={row.report_date} className="border-b border-border last:border-0 hover:bg-elevated/50 transition-colors">
                      <td className="px-3 py-2 font-mono text-text-secondary">{row.report_date}</td>
                      <td className="px-3 py-2 text-right font-mono text-text-primary">{row.eps_actual !== null ? row.eps_actual.toFixed(2) : "—"}</td>
                      <td className="px-3 py-2 text-right font-mono text-text-secondary">{row.eps_estimate !== null ? row.eps_estimate.toFixed(2) : "—"}</td>
                      <td className="px-3 py-2 text-right font-mono font-semibold" style={{ color: surpriseColor }}>
                        {surprise !== null ? `${surprise >= 0 ? "+" : ""}${surprise.toFixed(1)}%` : "—"}
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {optionsSnapshot && (
        <div>
          <h2 className="mb-2 text-xs font-semibold uppercase tracking-wider text-text-muted">
            Options Snapshot
            <span className="ml-2 font-normal normal-case text-text-muted">as of {optionsSnapshot.snapshot_date}</span>
          </h2>
          <div className="grid grid-cols-2 gap-2 sm:grid-cols-3 xl:grid-cols-5">
            <MetricCell label="IV Rank" value={optionsSnapshot.iv_rank !== null ? `${optionsSnapshot.iv_rank.toFixed(1)}%` : null} highlight={optionsSnapshot.iv_rank !== null ? optionsSnapshot.iv_rank >= 50 ? "#f59e0b" : "#6b7280" : undefined} />
            <MetricCell label="Put/Call" value={optionsSnapshot.pc_ratio !== null ? optionsSnapshot.pc_ratio.toFixed(2) : null} highlight={optionsSnapshot.pc_ratio !== null ? optionsSnapshot.pc_ratio >= 1.0 ? "#ef4444" : "#10b981" : undefined} />
            <MetricCell label="Max Pain" value={optionsSnapshot.max_pain !== null ? `$${optionsSnapshot.max_pain.toFixed(2)}` : null} />
            <MetricCell label="Call Wall" value={optionsSnapshot.call_wall !== null ? `$${optionsSnapshot.call_wall.toFixed(2)}` : null} highlight="#10b981" />
            <MetricCell label="Put Wall"  value={optionsSnapshot.put_wall !== null ? `$${optionsSnapshot.put_wall.toFixed(2)}` : null} highlight="#ef4444" />
          </div>
        </div>
      )}

      {insiderActivity && (
        <div>
          <div className="mb-2 flex items-center justify-between">
            <h2 className="text-xs font-semibold uppercase tracking-wider text-text-muted">Insider Activity</h2>
            <span
              className="rounded border px-2 py-0.5 text-2xs font-semibold"
              style={{
                color: insiderActivity.insider_sentiment === "bullish" ? "#10b981" : insiderActivity.insider_sentiment === "bearish" ? "#ef4444" : "#6b7280",
                background: insiderActivity.insider_sentiment === "bullish" ? "#10b98115" : insiderActivity.insider_sentiment === "bearish" ? "#ef444415" : "#6b728015",
                borderColor: insiderActivity.insider_sentiment === "bullish" ? "#10b98130" : insiderActivity.insider_sentiment === "bearish" ? "#ef444430" : "#6b728030",
              }}
            >
              {insiderActivity.insider_sentiment.charAt(0).toUpperCase() + insiderActivity.insider_sentiment.slice(1)}
            </span>
          </div>
          <div className="grid grid-cols-2 gap-2 sm:grid-cols-4 mb-3">
            <MetricCell label="Buys" value={String(insiderActivity.insider_buy_count)} highlight="#10b981" />
            <MetricCell label="Sells" value={String(insiderActivity.insider_sell_count)} highlight="#ef4444" />
            <MetricCell
              label="Buy Value"
              value={insiderActivity.insider_buy_value >= 1e6
                ? `$${(insiderActivity.insider_buy_value / 1e6).toFixed(1)}M`
                : insiderActivity.insider_buy_value > 0 ? `$${(insiderActivity.insider_buy_value / 1e3).toFixed(0)}K` : "—"}
              highlight="#10b981"
            />
            <MetricCell
              label="Net Flow"
              value={insiderActivity.insider_net_value >= 0
                ? `+$${(insiderActivity.insider_net_value / 1e6).toFixed(1)}M`
                : `-$${(Math.abs(insiderActivity.insider_net_value) / 1e6).toFixed(1)}M`}
              highlight={insiderActivity.insider_net_value >= 0 ? "#10b981" : "#ef4444"}
            />
          </div>
          {insiderActivity.transactions.slice(0, 5).length > 0 && (
            <div className="overflow-x-auto rounded-lg border border-border">
              <table className="w-full text-xs">
                <thead>
                  <tr className="border-b border-border bg-elevated">
                    <th className="px-3 py-2 text-left font-semibold text-text-muted">Date</th>
                    <th className="px-3 py-2 text-left font-semibold text-text-muted">Insider</th>
                    <th className="px-3 py-2 text-right font-semibold text-text-muted">Shares</th>
                    <th className="px-3 py-2 text-right font-semibold text-text-muted">Type</th>
                  </tr>
                </thead>
                <tbody>
                  {insiderActivity.transactions.slice(0, 5).map((txn, i) => (
                    <tr key={i} className="border-b border-border last:border-0 hover:bg-elevated/50 transition-colors">
                      <td className="px-3 py-2 font-mono text-text-secondary">{txn.date}</td>
                      <td className="px-3 py-2 text-text-primary truncate max-w-[120px]">{txn.insider}</td>
                      <td className="px-3 py-2 text-right font-mono text-text-secondary">
                        {txn.shares != null ? txn.shares.toLocaleString() : "—"}
                      </td>
                      <td className="px-3 py-2 text-right font-mono font-semibold"
                        style={{ color: txn.is_buy ? "#10b981" : txn.is_sell ? "#ef4444" : "#6b7280" }}>
                        {txn.is_buy ? "Buy" : txn.is_sell ? "Sell" : "—"}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
          <p className="mt-1.5 text-2xs text-text-muted">Chart markers: ▲ green = insider buy, ▼ red = insider sell. Click marker for detail.</p>
        </div>
      )}
    </>
  );

  // Pane 5 — Advanced tab
  const paneAdvanced = (
    <AdvancedTabContent
      ticker={upper}
      signal={signal}
      features={features}
      currentPrice={currentPrice}
      taSignals={taSignals}
      options={optionsSnapshot}
    />
  );

  // Pane 4 — bottom-right: TA Signals + Analyst
  const paneAnalysis = (
    <>
      <div className="rounded-lg border border-border bg-card p-4">
        <TASignalsPanel signals={taSignals} direction={taDirection} summary={taSummary} />
      </div>
      <div className="rounded-lg border border-border bg-card p-4">
        <h3 className="mb-3 text-xs font-semibold uppercase tracking-wider text-text-muted">Analyst Ratings</h3>
        <AnalystPanel fundamentals={fundamentals ?? null} currentPrice={currentPrice ?? undefined} />
      </div>
    </>
  );

  return (
    <main className="h-dvh flex flex-col bg-background text-text-primary">
      {/* ── Sticky header ─────────────────────────────────────────────────── */}
      <div className="flex-shrink-0 sticky top-0 z-30 border-b border-border bg-panel/95 backdrop-blur px-4 py-2.5 sm:px-5">
        <div className="flex flex-wrap items-center gap-3">
          <Link
            href="/dashboard"
            className="inline-flex items-center gap-1.5 rounded border border-border px-2.5 py-1.5 text-xs text-text-secondary transition-colors hover:border-accent-teal/50 hover:text-accent-teal"
          >
            <ArrowLeft className="h-3.5 w-3.5" />
            Dashboard
          </Link>

          <h1 className="font-mono text-xl font-bold text-text-primary">{upper}</h1>

          {currentPrice !== null && (
            <div className="flex items-baseline gap-1.5">
              <span className="font-mono text-lg font-semibold text-text-primary">${currentPrice.toFixed(2)}</span>
              {priceChange !== null && priceChangePct !== null && (
                <span className="font-mono text-sm font-medium" style={{ color: isPositive ? "#10b981" : "#ef4444" }}>
                  {isPositive ? "▲" : "▼"}{Math.abs(priceChange).toFixed(2)} ({isPositive ? "+" : ""}{priceChangePct.toFixed(2)}%)
                </span>
              )}
            </div>
          )}

          {signal && <SignalBadge signalClass={signal.signal_class} noTradeReason={signal.no_trade_reason} />}
          {features?.swing_candidate && (
            <span className="inline-flex items-center gap-1 rounded border border-blue-500/40 bg-blue-500/10 px-2 py-0.5 text-xs font-medium text-blue-400">
              ↔ Swing
            </span>
          )}
          {signal && <RayzarScore score={signal.rayzar_score} size="md" />}

          {fundamentals?.sector && (
            <span className="hidden sm:inline text-xs text-text-secondary">{fundamentals.sector}</span>
          )}
          {personality && (
            <span className="hidden sm:inline rounded border border-border bg-elevated px-2 py-0.5 font-mono text-xs text-text-secondary">
              {personality}
            </span>
          )}
          {macroRegime && <RegimePill label={`Macro: ${macroRegime}`} type={getRegimeType(macroRegime)} />}
          {sectorRegime && <RegimePill label={`Sector: ${sectorRegime}`} type={getRegimeType(sectorRegime)} />}

          <div className="ml-auto flex items-center gap-2">
            {signal?.signal_date && (
              <span className="hidden sm:inline text-xs text-text-muted">Signal: {signal.signal_date}</span>
            )}
            <WatchButton ticker={upper} size="md" />
          </div>
        </div>
      </div>

      {/* ── Tabs: [Chart] [Advanced] ─────────────────────────────────────── */}
      <StockPageTabs
        ticker={upper}
        chartContent={
          <WorkspaceLayout
            topLeft={paneChart}
            topRight={paneSignal}
            bottomLeft={paneData}
            bottomRight={paneAnalysis}
          />
        }
        advancedContent={paneAdvanced}
        currentPrice={currentPrice}
        signalClass={signal?.signal_class ?? null}
        hv20d={features?.hv_20d ?? null}
        atr14Pct={features?.atr14_pct ?? null}
      />

      {/* ── Disclaimer ────────────────────────────────────────────────────── */}
      <div className="flex-shrink-0 border-t border-border px-4 py-1.5 sm:px-6">
        <p className="text-2xs leading-relaxed text-text-muted line-clamp-1">
          {FINANCIAL_DISCLAIMER}
        </p>
      </div>
    </main>
  );
}
