/**
 * app/legal/page.tsx — RayZar Frontend
 * Legal disclaimer, risk warning, and terms of use.
 */

import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Legal Disclaimer — RayZar AI",
  description: "Risk disclaimer and terms of use for the RayZar AI Trading Intelligence platform.",
};

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mb-8">
      <h2 className="mb-3 text-base font-semibold text-text-primary border-b border-border pb-2">
        {title}
      </h2>
      <div className="space-y-3 text-sm text-text-secondary leading-relaxed">
        {children}
      </div>
    </section>
  );
}

export default function LegalPage() {
  return (
    <main className="mx-auto max-w-3xl px-4 py-12">
      {/* Header */}
      <div className="mb-10">
        <Link
          href="/dashboard"
          className="mb-6 inline-flex items-center gap-1.5 text-xs text-text-muted hover:text-text-secondary transition-colors"
        >
          ← Back to Dashboard
        </Link>
        <h1 className="text-2xl font-bold text-text-primary tracking-tight">
          Legal Disclaimer &amp; Risk Warning
        </h1>
        <p className="mt-2 text-sm text-text-muted">
          Last updated: April 2026 · Effective immediately
        </p>
      </div>

      {/* Critical warning banner */}
      <div
        className="mb-8 rounded-lg border px-5 py-4"
        style={{
          borderColor: "rgba(239,68,68,0.3)",
          background: "rgba(239,68,68,0.05)",
        }}
      >
        <p className="text-sm font-semibold text-red-400 mb-1">
          NOT FINANCIAL ADVICE
        </p>
        <p className="text-sm text-text-secondary leading-relaxed">
          RayZar AI is an informational and educational tool only. Nothing on this platform
          constitutes financial, investment, legal, or tax advice. All signals, scores, and
          analysis are generated by automated machine learning models and must not be relied
          upon for actual investment decisions.
        </p>
      </div>

      <Section title="1. No Investment Advice">
        <p>
          RayZar AI Trading Intelligence (&ldquo;RayZar&rdquo;, &ldquo;we&rdquo;, &ldquo;the platform&rdquo;) provides
          market analysis, algorithmic signals, and data visualisations for <strong className="text-text-primary">
          informational and educational purposes only</strong>. The content, signals, scores, charts,
          and commentary provided by RayZar do not constitute investment advice, financial advice,
          trading advice, or any other type of advice.
        </p>
        <p>
          No content on this platform should be construed as a recommendation to buy, sell, or hold
          any security, financial instrument, or asset. You should always seek independent financial
          advice from a qualified professional before making any investment decisions.
        </p>
      </Section>

      <Section title="2. Risk Warning">
        <p>
          <strong className="text-text-primary">Trading and investing involve substantial risk of financial loss.</strong>{" "}
          The value of securities can fall as well as rise, and you may receive back less than you originally invested.
          Past performance of any signal, model, or strategy is not a reliable indicator of future results.
        </p>
        <p>
          Algorithmic trading models, including those used by RayZar, are subject to model risk, data risk,
          overfitting, and can fail in unexpected market conditions. Walk-forward validation and backtesting
          results shown on the platform are historical and may not reflect future performance.
        </p>
        <p>
          You should never invest money that you cannot afford to lose. Before using any signal or
          analysis from this platform, ensure you fully understand the risks involved and, where appropriate,
          seek professional advice.
        </p>
      </Section>

      <Section title="3. No Guarantee of Accuracy">
        <p>
          RayZar makes no representations or warranties, express or implied, as to the accuracy,
          completeness, reliability, or timeliness of any information provided on this platform.
          Signal data, price data, fundamental data, and analyst estimates are sourced from third-party
          providers and may contain errors, omissions, or delays.
        </p>
        <p>
          Machine learning models used to generate signals are trained on historical data and may
          not perform as expected in live market conditions. Signal classifications (STRONG LONG,
          LONG, NEUTRAL, SHORT, STRONG SHORT, NO TRADE) are model outputs — not guarantees of
          price direction.
        </p>
      </Section>

      <Section title="4. Model Limitations">
        <p>
          RayZar signals are generated by ensemble machine learning models trained on historical
          price, volume, technical indicator, fundamental, options, and sentiment data. These models
          have inherent limitations:
        </p>
        <ul className="list-disc pl-5 space-y-1.5 text-text-secondary">
          <li>Models are trained on past data and may not generalise to future market regimes.</li>
          <li>Black swan events, geopolitical shocks, and liquidity crises are not captured.</li>
          <li>Model performance degrades over time and requires periodic retraining.</li>
          <li>Signal confidence scores are probability estimates, not certainties.</li>
          <li>The platform does not account for transaction costs, slippage, or taxes.</li>
        </ul>
      </Section>

      <Section title="5. Informational Use Only">
        <p>
          RayZar is intended for use by individuals who wish to supplement their own research and
          decision-making process. The platform is <strong className="text-text-primary">not a brokerage,
          not a registered investment advisor, and not a regulated financial services provider</strong>.
        </p>
        <p>
          Use of this platform does not create any fiduciary duty, advisory relationship, or
          client relationship between you and RayZar.
        </p>
      </Section>

      <Section title="6. Third-Party Data">
        <p>
          Price data, fundamental data, earnings data, options data, and insider activity data
          are sourced from third-party providers including Yahoo Finance, financial data APIs,
          and public SEC filings. RayZar is not responsible for the accuracy or completeness
          of third-party data.
        </p>
      </Section>

      <Section title="7. Limitation of Liability">
        <p>
          To the fullest extent permitted by law, RayZar and its operators shall not be liable for
          any direct, indirect, incidental, special, consequential, or punitive damages arising from
          your use of or reliance on this platform, including but not limited to trading losses,
          lost profits, or investment decisions made based on platform content.
        </p>
      </Section>

      <Section title="8. Acceptance of Terms">
        <p>
          By accessing and using the RayZar platform, you acknowledge that you have read,
          understood, and agree to this disclaimer in full. If you do not agree with any part
          of this disclaimer, you must not use the platform.
        </p>
      </Section>

      {/* Footer nav */}
      <div className="mt-10 border-t border-border pt-6 flex items-center justify-between text-xs text-text-muted">
        <span>© 2026 RayZar AI. All rights reserved.</span>
        <Link href="/dashboard" className="hover:text-text-secondary transition-colors">
          Back to Dashboard →
        </Link>
      </div>
    </main>
  );
}
